son1=int(input("Birinchi sonni kiriting: "))
son2=int(input("Ikkinchi sonni kiriting: "))
son3=int(input("Uchinchi sonni kiriting: "))
engkatta =max(son1,son2,son3)
engkichik =min(son1,son2,son3)
print("Engkattasi = ",engkatta)
print("Engkichigi = ",engkichik)